### ISSUE TITLE
`NewMessageEvent` Not received

### ISSUE THREAD

**Issue by glung** [GetStream/stream-chat-android-client#11]
**Describe the bug**
The `NewMessageEvent`s are not received. The chat client is connected, and `health.check` events are received.

To test, I use an Android version see below and the vanilla react example (using the same api-key and a different user).

- Messages sent from the Android app are received by the React app
- Messages sent from the React app are **not** received by the Android app
- Messages sent from the React app are received by another instance of the React app

Android version:
```
class GetStreamChatClient(private val loggedInUser: User, context: Context) {
    private var client: ChatClient

    init {
        client = ChatClient.Builder(API_KEY, context).build()
        client.channel(CHANNEL_TYPE, CHANNEL_ID).events()
        client.setUser(
            GetStreamUser(loggedInUser.name),
            LOGGEDIN_USER_TOKEN,
            object : InitConnectionListener() {
                override fun onSuccess(data: ConnectionData) {
                    listen()
                }
            }
        )
    }

    fun listen() {
        client
            .events()
            .subscribe { event: ChatEvent ->
                logDebug(event.toString())
                if (event is NewMessageEvent) {
                   // doSomething
                }
            }
    }

    override fun sendMessage(content: String) {
        client.sendMessage(
            CHANNEL_TYPE,
            CHANNEL_ID,
            GetStreamMessage(text = content)
        ).enqueue { result: Result<GetStreamMessage> ->
            logDebug(result.toString())
        }
    }
}
```

**SDK version**
- 1.2.0

**Comment by tschellenbach** [comment]
Hi Guillaume thanks for reaching out. What are you working on?

**Comment by tschellenbach** [comment]
What's the output for result.toString()?

**Comment by tschellenbach** [comment]
Ah I think you're missing a call to client.channel(CHANNEL_TYPE, CHANNEL_ID).watch()

**Comment by tschellenbach** [comment]
And while you're here, which version of android are you targeting and do you prefer to use RX or LiveData?

**Comment by glung** [comment]
Thank you @tschellenbach, calling `watch` on the channel was indeed missing. It works now if I wait for the watch call to complete, before calling `subscribe`. 

Since we are at it, I also noticed that the User id comes back with an id postfixed with `User ID`. For instance, when I set my user id to be "me", the message events will be attributed to the `User` with `id` `meUser ID`. Is it expected? 

To answer your question, I'm just playing with the getstream/chat (that's why I'm happy to be able to use the low-level API - without UI).

**Comment by tschellenbach** [comment]
User id's aren't postfixed as far as I know. @elevenetc ?

**Comment by elevenetc** [comment]
Yeah, there should not be any postfix.
@glung  What is `GetStreamUser`? 

And few things about SDK behaviour:
- `client.events()` returns stateless observable. So you can subscribe wherever and whenever you want.
- `InitConnectionListener` is better to use for integration purposes only. It's called only once, so when socket is disconnected and connected again `onSuccess` will not be called again. So better alternative is `client.events()`.

Your code might look like this:
```kotlin
class GetStreamChatClient(private val loggedInUser: User, context: Context) {
    private var client: ChatClient

    init {
        client = ChatClient.Builder(API_KEY, context).build()
        listen()
        client.setUser(GetStreamUser(loggedInUser.name) LOGGEDIN_USER_TOKEN)
    }

    // the rest of the code
}
```

**Comment by glung** [comment]
@elevenetc I tried your suggestion, it does not work for me. If the user is not set, then listening to events does not work. In the [doc here](https://getstream.io/chat/docs/init_and_users/?language=kotlin), it is written:

> Note how we are waiting for the setUser API call to be completed before moving forward. You should always make sure to have the user set before making any more calls. All SDKs make this very easy and wait or queue requests until then.

That's why I was thinking about using `InitConnectionListener`. 

Don't worry about the `GetStream[...]` prefix, it's just an alias.
```
import io.getstream.chat.android.client.models.Message as GetStreamMessage
import io.getstream.chat.android.client.models.User as GetStreamUser
```

**Comment by elevenetc** [comment]
I didn't suggest to not call `setUser`. It's indeed needed for calls, because `setUser` defines user and token and both these params are required for calling api. But `client.events()` doesn't connected to any internal state of client, it just returns observable which distributes client events:
```kotlin
client.events()
	.filter(ConnectedEvent::class.java)
	.filter(DisconnectedEvent::class.java)
	.filter(ConnectingEvent::class.java)
	.subscribe { event -> 
		println("Connection status: " + event.type)
	}

client.setUser()
client.disconnected()
client.setUser()
```
And documentation is misleading right now with this line: `All SDKs make this very easy and wait or queue requests until then`. Just few weeks earlier we introduced extracted client which responsible for network communication only. Before we had SDK which contains everything (including UI) and it supports requests queueing until `setUser` is called.

------
Going back to user user id prefix, still not sure how that happens. Could you check logcat logs? You can filter SDK logs by chat prefix `adb pidcat | grep "Chat"`. 
There be should log of setting up socket connection with user:
```
04-25 19:58:10.359 25439 25439 I Chat:SocketService: httpClient.newWebSocket: wss://chat-us-east-1.stream-io-api.com/connect?json=%7B%22user_details%22%3A%7B%22role%22%3A%22%22%2C%22devices%22%3A%5B%5D%2C%22invisible%22%3Afalse%2C%22banned%22%3Afalse%2C%22id%22%3A%22stream-eugene%22%7D%2C%22user_id%22%3A%22stream-eugene%22%2C%22server_determines_connection_id%22%3Atrue%2C%22X-STREAM-CLIENT%22%3A%221.1.0-debug%22%7D
```
Which can be url decoded into:
```json
{
  "user_details": {
    "role": "",
    "devices": [
      
    ],
    "invisible": false,
    "banned": false,
    "id": "stream-eugene"
  },
  "user_id": "stream-eugene",
  "server_determines_connection_id": true,
  "X-STREAM-CLIENT": "1.1.0-debug"
}
```
And connection event with the user data:
```
04-25 19:58:11.340 25439 25531 I Chat:Events: onMessage: 
{
  "type": "health.check",
  "connection_id": "b7379f91-1c61-4ccc-8ee7-d9a983929102",
  "cid": "*",
  "me": {
    "id": "stream-eugene",
    "role": "user",
    "created_at": "2020-04-02T17:55:03.278292Z",
    "updated_at": "2020-04-25T17:58:11.373249Z",
    "last_active": "2020-04-25T17:58:11.376815688Z",
    "banned": false,
    "online": true,
    "invisible": false,
    "devices": [
      
    ],
    "mutes": [
      
    ],
    "channel_mutes": [
      
    ],
    "unread_count": 6,
    "total_unread_count": 6,
    "unread_channels": 1,
    "name": "stream-eugene",
    "image": "https://bit.ly/31EzdNK"
  },
  "created_at": "2020-04-25T17:58:11.38276851Z"
}
```

**Comment by glung** [comment]
When using the code below, I noticed that the method that subscribes just after the `setUser` call (`expectNoEventsReceived`) does not receive events. The other one that waits for the `setUser` success callback to subscribe does receive events. 

What I have done: 

**Method 0:**
- start a react chat in the browser (same API key, same channel, different user)
- start the Android app and call `GetstreamChatClient(context).expectNoEventsReceived()`
- the react app receives the message `"Started method0"`
- send a message "XYZ" with the react app
- expect a new message to be received on Android (in the logs)
- actually, only health checks are received 

**Method 1:**
- start a react chat in the browser (same API key, same channel, different user)
- start the Android app and call `GetstreamChatClient(context).expectEventsReceived()`
- the react app receives the message `"Started method1"`
- send a message "XYZ" with the react app
- a new message to be received on Android (in the logs) (success case)

```kotlin
package com.getstream

import android.content.Context
import io.getstream.chat.android.client.ChatClient
import io.getstream.chat.android.client.models.Message
import io.getstream.chat.android.client.models.User
import io.getstream.chat.android.client.socket.InitConnectionListener

class GetstreamChatClient(private val context: Context) {

    fun expectNoEventsReceived() {
        val client = ChatClient.Builder(API_KEY, context).build()
        val channelController = client.channel(CHANNEL_TYPE, CHANNEL_ID)

        channelController
            .watch()
            .enqueue()

        channelController
            .events()
            .subscribe { println("Event received: $it") }

        client.setUser(
            User(id = USER_ID),
            LOGGEDIN_USER_TOKEN
        )

        channelController.sendMessage(Message(text = "Started method0")).enqueue()
    }

    fun expectEventsReceived() {
        val client = ChatClient.Builder(API_KEY, context).build()
        val channelController = client.channel(CHANNEL_TYPE, CHANNEL_ID)


        client.setUser(
            User(id = USER_ID),
            LOGGEDIN_USER_TOKEN,
            object : InitConnectionListener() {
                override fun onSuccess(data: ConnectionData) {
                    channelController
                        .watch()
                        .enqueue()

                    channelController
                        .events()
                        .subscribe { println("Event received: $it") }

                    channelController.sendMessage(Message(text = "Started method1")).enqueue()
                }
            }
        )
    }
}
```

---

About the user ID suffix, I'm afraid that I probably made a stupid mistake myself [when creating the JWT token](https://getstream.io/chat/docs/token_generator/?language=js) 🙈 I believe I pasted the name and the place holder ("User ID") postfixed the username. 

The JWT token probably encoded a user-id postfixed by "User ID". My bad 🙈 

I did not know that a user-id was embedded in the JWT and that it would take precedence over the user_id in the User object when calling `ChatClient.setUser(user: User, token: String)`

**Comment by tschellenbach** [comment]
@glung assuming you're using livedata you might also enjoy this lib: https://getstream.io/chat/docs/livedata/?language=kotlin

**Comment by elevenetc** [comment]
@glung debugged your code and the problem that `channelController.watch().enqueue()` is finished with error. If you pass callback into `enqueue` you will see the error message:
```
setUser is either not called or not finished
```
That's why you're not getting channel updates. 
So to make api calls (like watch, or query channels) you need to call setUser and wait when it's finished. To understand when it's finished you have two options:
1. with `InitConnectionListener` like your did already
2. with `ConnectedEvent`:
```kotlin
client.events().subscribe {
    if(it is ConnectedEvent) channelController.watch().enqueue()
}
```

**Comment by tschellenbach** [comment]
@glung following up here, did this help resolve your issue?

Also note that we increased the size of our android team, SDKs are improving quite rapidly at the moment.

**Comment by glung** [comment]
@tschellenbach oh I forgot to reply! This has been really useful to understand how it works and get it fixed. In the end, I went with the `InitConnectionListener` approach. Thx @elevenetc
