### ISSUE TITLE
Can't add new members to channel 

### ISSUE THREAD

**Issue by soethan98** [GetStream/stream-chat-android-client#23]
Can't add members to channel even by the owner of the channel in android. 
**Result in 201 error API key not found**. It hitting wrong URL  when **addMembers()** is called with  wrong placement of the API key in path of the URL  and channel id in the query parameter.

E.g - https://chat-us-east-1.stream-io-api.com/channels/messaging/{api_key}/query?api_key={channel_id}&user_id=xxx&client_id=xxx

**Comment by elevenetc** [comment]
Thanks for report. Wrong api key parameter is passed indeed. Fix will be released soon.

**Comment by elevenetc** [comment]
Released in 1.4.10 https://github.com/GetStream/stream-chat-android-client/releases/tag/1.4.10
