### ISSUE TITLE
Missing autocomplete filter definition

### ISSUE THREAD

**Issue by pixnbit** [GetStream/stream-chat-android-client#50]
There's all there to it in the Filters:

```kotlin
      val autocomplete = FilterObject(
          field,
          FilterObject("\$autocomplete", query)
      )
```

The documentation is missing with how to do autocomplete with it too for Kotin:
https://getstream.io/chat/docs/query_users/?language=kotlin

**Comment by adasiewiczr** [comment]
Hi, @pixnbit thanks for reporting that. It was resolved in #94  and will be released in the next version
